/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * API version: 1.0.1
 * Contact: dev@approveapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package approveapi

type Prompt struct {
	// The unix timestamp when this prompt was sent.
	SentAt float32 `json:"sent_at"`
	Answer *PromptAnswer `json:"answer,omitempty"`
	// Whether the prompt can still be answered.
	IsExpired bool `json:"is_expired"`
	Request CreatePromptRequest `json:"request"`
	// A unique id for this prompt.
	Id string `json:"id"`
	Metadata *PromptMetadata `json:"metadata,omitempty"`
}
