/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * API version: 1.0.0
 * Contact: dev@approveapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package approveapi

type AnswerMetadata struct {
	OperatingSystem string `json:"operating_system,omitempty"`
	IpAddress string `json:"ip_address,omitempty"`
	Browser string `json:"browser,omitempty"`
}
