/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * API version: 1.0.0
 * Contact: dev@approveapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package approveapi

type Prompt struct {
	Answer PromptAnswer `json:"answer,omitempty"`
	// The unix timestamp when this prompt was sent.
	SentAt float32 `json:"sent_at"`
	// A unique id for this prompt.
	Id string `json:"id"`
	// The unix timestamp when this prompt can no longer be answered.
	ExpiresAt float32 `json:"expires_at,omitempty"`
	Metadata PromptMetadata `json:"metadata,omitempty"`
}
