/*
 * ApproveAPISwagger
 *
 * The simple API to request a user's approval on anything via email + sms.
 *
 * API version: 1.0.1
 * Contact: dev@approveapi.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package approveapi

type AnswerMetadata struct {
	SlackRealName *string `json:"slack_real_name,omitempty"`
	OperatingSystem *string `json:"operating_system,omitempty"`
	SlackUsername *string `json:"slack_username,omitempty"`
	IpAddress *string `json:"ip_address,omitempty"`
	SlackEmail *string `json:"slack_email,omitempty"`
	Browser *string `json:"browser,omitempty"`
}
